# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: mcr.microsoft.com/dotnet/core/sdk:3.1
pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: 
          - export SOLUTION_NAME=Promenade          
          - export CONFIGURATION=Release
    - export WEB_PROJECT_NAME=Web
          - export REPORTS_REL_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}  
          - dotnet restore $SOLUTION_NAME.sln
          - dotnet build --no-restore $SOLUTION_NAME.sln --configuration $CONFIGURATION
          - dotnet test --no-build $SOLUTION_NAME.sln --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_REL_PATH/junit.xml"
          - dotnet publish --configuration $CONFIGURATION --no-build ./Web/${WEB_PROJECT_NAME}.csproj -o ./publish
        artifacts: 
          - ./publish/**